/*
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.mydsl.myDsl.Facet;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.Normalvector;
import org.xtext.example.mydsl.myDsl.Solid;
import org.xtext.example.mydsl.myDsl.Vector;
import org.xtext.example.mydsl.services.MyDslGrammarAccess;

@SuppressWarnings("all")
public class MyDslSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private MyDslGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == MyDslPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case MyDslPackage.FACET:
				sequence_Facet(context, (Facet) semanticObject); 
				return; 
			case MyDslPackage.NORMALVECTOR:
				sequence_Normalvector(context, (Normalvector) semanticObject); 
				return; 
			case MyDslPackage.SOLID:
				sequence_Solid(context, (Solid) semanticObject); 
				return; 
			case MyDslPackage.VECTOR:
				sequence_Vector(context, (Vector) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     Facet returns Facet
	 *
	 * Constraint:
	 *     (normal=Normalvector v1=Vector v2=Vector v3=Vector)
	 */
	protected void sequence_Facet(ISerializationContext context, Facet semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.FACET__NORMAL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.FACET__NORMAL));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.FACET__V1) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.FACET__V1));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.FACET__V2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.FACET__V2));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.FACET__V3) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.FACET__V3));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFacetAccess().getNormalNormalvectorParserRuleCall_1_0(), semanticObject.getNormal());
		feeder.accept(grammarAccess.getFacetAccess().getV1VectorParserRuleCall_4_0(), semanticObject.getV1());
		feeder.accept(grammarAccess.getFacetAccess().getV2VectorParserRuleCall_5_0(), semanticObject.getV2());
		feeder.accept(grammarAccess.getFacetAccess().getV3VectorParserRuleCall_6_0(), semanticObject.getV3());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Normalvector returns Normalvector
	 *
	 * Constraint:
	 *     (x1=FLOAT x2=FLOAT x3=FLOAT)
	 */
	protected void sequence_Normalvector(ISerializationContext context, Normalvector semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.NORMALVECTOR__X1) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.NORMALVECTOR__X1));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.NORMALVECTOR__X2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.NORMALVECTOR__X2));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.NORMALVECTOR__X3) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.NORMALVECTOR__X3));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getNormalvectorAccess().getX1FLOATTerminalRuleCall_1_0(), semanticObject.getX1());
		feeder.accept(grammarAccess.getNormalvectorAccess().getX2FLOATTerminalRuleCall_2_0(), semanticObject.getX2());
		feeder.accept(grammarAccess.getNormalvectorAccess().getX3FLOATTerminalRuleCall_3_0(), semanticObject.getX3());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Solid returns Solid
	 *
	 * Constraint:
	 *     (name=ID facets+=Facet+)
	 */
	protected void sequence_Solid(ISerializationContext context, Solid semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Vector returns Vector
	 *
	 * Constraint:
	 *     (x1=FLOAT x2=FLOAT x3=FLOAT)
	 */
	protected void sequence_Vector(ISerializationContext context, Vector semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.VECTOR__X1) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.VECTOR__X1));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.VECTOR__X2) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.VECTOR__X2));
			if (transientValues.isValueTransient(semanticObject, MyDslPackage.Literals.VECTOR__X3) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, MyDslPackage.Literals.VECTOR__X3));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getVectorAccess().getX1FLOATTerminalRuleCall_1_0(), semanticObject.getX1());
		feeder.accept(grammarAccess.getVectorAccess().getX2FLOATTerminalRuleCall_2_0(), semanticObject.getX2());
		feeder.accept(grammarAccess.getVectorAccess().getX3FLOATTerminalRuleCall_3_0(), semanticObject.getX3());
		feeder.finish();
	}
	
	
}
