/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslFactory
 * @model kind="package"
 * @generated
 */
public interface MyDslPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "myDsl";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/MyDsl";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "myDsl";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslPackage eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.SolidImpl <em>Solid</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.SolidImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSolid()
   * @generated
   */
  int SOLID = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOLID__NAME = 0;

  /**
   * The feature id for the '<em><b>Facets</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOLID__FACETS = 1;

  /**
   * The number of structural features of the '<em>Solid</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOLID_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.FacetImpl <em>Facet</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.FacetImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFacet()
   * @generated
   */
  int FACET = 1;

  /**
   * The feature id for the '<em><b>Normal</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACET__NORMAL = 0;

  /**
   * The feature id for the '<em><b>V1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACET__V1 = 1;

  /**
   * The feature id for the '<em><b>V2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACET__V2 = 2;

  /**
   * The feature id for the '<em><b>V3</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACET__V3 = 3;

  /**
   * The number of structural features of the '<em>Facet</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FACET_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.VectorImpl <em>Vector</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.VectorImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVector()
   * @generated
   */
  int VECTOR = 2;

  /**
   * The feature id for the '<em><b>X1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VECTOR__X1 = 0;

  /**
   * The feature id for the '<em><b>X2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VECTOR__X2 = 1;

  /**
   * The feature id for the '<em><b>X3</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VECTOR__X3 = 2;

  /**
   * The number of structural features of the '<em>Vector</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VECTOR_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.myDsl.impl.NormalvectorImpl <em>Normalvector</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.myDsl.impl.NormalvectorImpl
   * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNormalvector()
   * @generated
   */
  int NORMALVECTOR = 3;

  /**
   * The feature id for the '<em><b>X1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMALVECTOR__X1 = 0;

  /**
   * The feature id for the '<em><b>X2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMALVECTOR__X2 = 1;

  /**
   * The feature id for the '<em><b>X3</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMALVECTOR__X3 = 2;

  /**
   * The number of structural features of the '<em>Normalvector</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NORMALVECTOR_FEATURE_COUNT = 3;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Solid <em>Solid</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Solid</em>'.
   * @see org.xtext.example.mydsl.myDsl.Solid
   * @generated
   */
  EClass getSolid();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Solid#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.myDsl.Solid#getName()
   * @see #getSolid()
   * @generated
   */
  EAttribute getSolid_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.myDsl.Solid#getFacets <em>Facets</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Facets</em>'.
   * @see org.xtext.example.mydsl.myDsl.Solid#getFacets()
   * @see #getSolid()
   * @generated
   */
  EReference getSolid_Facets();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Facet <em>Facet</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Facet</em>'.
   * @see org.xtext.example.mydsl.myDsl.Facet
   * @generated
   */
  EClass getFacet();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Facet#getNormal <em>Normal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Normal</em>'.
   * @see org.xtext.example.mydsl.myDsl.Facet#getNormal()
   * @see #getFacet()
   * @generated
   */
  EReference getFacet_Normal();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Facet#getV1 <em>V1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>V1</em>'.
   * @see org.xtext.example.mydsl.myDsl.Facet#getV1()
   * @see #getFacet()
   * @generated
   */
  EReference getFacet_V1();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Facet#getV2 <em>V2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>V2</em>'.
   * @see org.xtext.example.mydsl.myDsl.Facet#getV2()
   * @see #getFacet()
   * @generated
   */
  EReference getFacet_V2();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.myDsl.Facet#getV3 <em>V3</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>V3</em>'.
   * @see org.xtext.example.mydsl.myDsl.Facet#getV3()
   * @see #getFacet()
   * @generated
   */
  EReference getFacet_V3();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Vector <em>Vector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Vector</em>'.
   * @see org.xtext.example.mydsl.myDsl.Vector
   * @generated
   */
  EClass getVector();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Vector#getX1 <em>X1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X1</em>'.
   * @see org.xtext.example.mydsl.myDsl.Vector#getX1()
   * @see #getVector()
   * @generated
   */
  EAttribute getVector_X1();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Vector#getX2 <em>X2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X2</em>'.
   * @see org.xtext.example.mydsl.myDsl.Vector#getX2()
   * @see #getVector()
   * @generated
   */
  EAttribute getVector_X2();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Vector#getX3 <em>X3</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X3</em>'.
   * @see org.xtext.example.mydsl.myDsl.Vector#getX3()
   * @see #getVector()
   * @generated
   */
  EAttribute getVector_X3();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.myDsl.Normalvector <em>Normalvector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Normalvector</em>'.
   * @see org.xtext.example.mydsl.myDsl.Normalvector
   * @generated
   */
  EClass getNormalvector();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Normalvector#getX1 <em>X1</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X1</em>'.
   * @see org.xtext.example.mydsl.myDsl.Normalvector#getX1()
   * @see #getNormalvector()
   * @generated
   */
  EAttribute getNormalvector_X1();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Normalvector#getX2 <em>X2</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X2</em>'.
   * @see org.xtext.example.mydsl.myDsl.Normalvector#getX2()
   * @see #getNormalvector()
   * @generated
   */
  EAttribute getNormalvector_X2();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.myDsl.Normalvector#getX3 <em>X3</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>X3</em>'.
   * @see org.xtext.example.mydsl.myDsl.Normalvector#getX3()
   * @see #getNormalvector()
   * @generated
   */
  EAttribute getNormalvector_X3();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MyDslFactory getMyDslFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.SolidImpl <em>Solid</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.SolidImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getSolid()
     * @generated
     */
    EClass SOLID = eINSTANCE.getSolid();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SOLID__NAME = eINSTANCE.getSolid_Name();

    /**
     * The meta object literal for the '<em><b>Facets</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SOLID__FACETS = eINSTANCE.getSolid_Facets();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.FacetImpl <em>Facet</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.FacetImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getFacet()
     * @generated
     */
    EClass FACET = eINSTANCE.getFacet();

    /**
     * The meta object literal for the '<em><b>Normal</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FACET__NORMAL = eINSTANCE.getFacet_Normal();

    /**
     * The meta object literal for the '<em><b>V1</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FACET__V1 = eINSTANCE.getFacet_V1();

    /**
     * The meta object literal for the '<em><b>V2</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FACET__V2 = eINSTANCE.getFacet_V2();

    /**
     * The meta object literal for the '<em><b>V3</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FACET__V3 = eINSTANCE.getFacet_V3();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.VectorImpl <em>Vector</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.VectorImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getVector()
     * @generated
     */
    EClass VECTOR = eINSTANCE.getVector();

    /**
     * The meta object literal for the '<em><b>X1</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VECTOR__X1 = eINSTANCE.getVector_X1();

    /**
     * The meta object literal for the '<em><b>X2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VECTOR__X2 = eINSTANCE.getVector_X2();

    /**
     * The meta object literal for the '<em><b>X3</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VECTOR__X3 = eINSTANCE.getVector_X3();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.myDsl.impl.NormalvectorImpl <em>Normalvector</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.myDsl.impl.NormalvectorImpl
     * @see org.xtext.example.mydsl.myDsl.impl.MyDslPackageImpl#getNormalvector()
     * @generated
     */
    EClass NORMALVECTOR = eINSTANCE.getNormalvector();

    /**
     * The meta object literal for the '<em><b>X1</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NORMALVECTOR__X1 = eINSTANCE.getNormalvector_X1();

    /**
     * The meta object literal for the '<em><b>X2</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NORMALVECTOR__X2 = eINSTANCE.getNormalvector_X2();

    /**
     * The meta object literal for the '<em><b>X3</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute NORMALVECTOR__X3 = eINSTANCE.getNormalvector_X3();

  }

} //MyDslPackage
