/**
 * generated by Xtext 2.15.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Normalvector</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Normalvector#getX1 <em>X1</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Normalvector#getX2 <em>X2</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.Normalvector#getX3 <em>X3</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNormalvector()
 * @model
 * @generated
 */
public interface Normalvector extends EObject
{
  /**
   * Returns the value of the '<em><b>X1</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>X1</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>X1</em>' attribute.
   * @see #setX1(float)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNormalvector_X1()
   * @model
   * @generated
   */
  float getX1();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Normalvector#getX1 <em>X1</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X1</em>' attribute.
   * @see #getX1()
   * @generated
   */
  void setX1(float value);

  /**
   * Returns the value of the '<em><b>X2</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>X2</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>X2</em>' attribute.
   * @see #setX2(float)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNormalvector_X2()
   * @model
   * @generated
   */
  float getX2();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Normalvector#getX2 <em>X2</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X2</em>' attribute.
   * @see #getX2()
   * @generated
   */
  void setX2(float value);

  /**
   * Returns the value of the '<em><b>X3</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>X3</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>X3</em>' attribute.
   * @see #setX3(float)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getNormalvector_X3()
   * @model
   * @generated
   */
  float getX3();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.Normalvector#getX3 <em>X3</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>X3</em>' attribute.
   * @see #getX3()
   * @generated
   */
  void setX3(float value);

} // Normalvector
