///*
// * generated by Xtext 2.15.0
// */
//package org.xtext.example.mydsl.tests
//
//import com.google.inject.Inject
//import org.eclipse.xtext.testing.InjectWith
//import org.eclipse.xtext.testing.extensions.InjectionExtension
//import org.eclipse.xtext.testing.util.ParseHelper
//import org.junit.jupiter.api.Test
//import org.junit.jupiter.api.^extension.ExtendWith
//import org.xtext.example.mydsl.myDsl.Solid
//
//@ExtendWith(InjectionExtension)
//@InjectWith(MyDslInjectorProvider)
//class MyDslParsingTest {
//	@Inject
//	ParseHelper<Solid> parseHelper
//	
//	@Test
//	def void loadModel() {
//		
//		val file = parseHelper.parse('''
//solid OpenSCAD_Model
//  facet normal -0.999391 0 -0.0348995
//    outer loop
//      vertex -30.4581 -5 10.3465
//      vertex -30.4581 5 10.3465
//      vertex -30.4568 -5.62667 10.3071
//    endloop
//  endfacet
//  facet normal -0.999391 0 -0.0348995
//    outer loop
//      vertex -30.4568 -5.62667 10.3071
//      vertex -30.4581 5 10.3465
//      vertex -30.4568 5.62667 10.3071
//    endloop
//  endfacet
//  endsolid OpenSCAD_Model
//        ''')
//        
//       	println("Name: " + file.name );
//       	val facets = file.facets;
//       	for(x: facets) {
//       		println("\nFacet: ")
//       		val normal = x.normal;
//       		println("Normalvector: " + normal.getX1() + " "  + normal.getX2() + " " + normal.getX3());
//       		val v = x.getV1();
//       		println("Vector1 : " + v.getX1() + " "  + v.getX2() + " " + v.getX3());
//       		val z = x.getV2();
//       		println("Vector2 : " + z.getX1() + " "  + z.getX2() + " " + z.getX3());
//       		val w = x.getV3();
//       		println("Vector3 : " + w.getX1() + " "  + w.getX2() + " " + w.getX3());
//       		   		
//
//       	}
//	}
//}
